### ISSUE TITLE
There is no result list after search.

### ISSUE THREAD

**Issue by zyqhi** [mtth/locate.vim#3] opened 2015-05-25 05:41 UTC
After search, results are highlighted, but there is no result list.
I am using macvim7.4

**Comment by mtth** [comment] 2015-05-25 14:41
Does the list open when you run `:lopen` after a search? Do `:lnext` and `:lprevious` work after a search with multiple matches? Also, what other plugins are you using?

**Comment by zyqhi** [comment] 2015-05-26 15:12
List is opened after I run `:lopen`, but it's not opened automatically after a search. But now, the matched strings are not highlighted. 
Here is a list of vim plugin in my `.vimrc`
```
Bundle 'gmarik/vundle'
Bundle 'tpope/vim-bundler'

Bundle 'thoughtbot/vim-rspec'
Bundle 'ack.vim'
Bundle 'comments.vim'
Bundle 'ctrlp.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'rspec.vim'
Bundle 'honza/vim-snippets'
Bundle 'scrooloose/syntastic'
Bundle 'kchmck/vim-coffee-script'
Bundle 'flazz/vim-colorschemes'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-rails'
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'pangloss/vim-javascript'
Bundle 'jelera/vim-javascript-syntax'
Bundle 'briancollins/vim-jst'
Bundle 'plasticboy/vim-markdown'
Bundle 'Lokaltog/vim-powerline'
Bundle 'vim-ruby/vim-ruby'
Bundle 'slim-template/vim-slim'
Bundle 'sudo.vim'
Bundle 'xml.vim'
Bundle 'ZenCoding.vim'

Bundle 'junegunn/goyo.vim'
Bundle 'junegunn/limelight.vim'

Bundle 'vim-scripts/Mark--Karkat'
" 导致CtabRedoIndent错误
" Bundle 'vim-scripts/Smart-Tabs'
Bundle 'vim-scripts/TagHighlight'
" Bundle 'vim-scripts/mru.vim'
Bundle 'yegappan/mru'

" Bundle 'drmingdrmer/xptemplate'
Bundle 'wesleyche/SrcExpl'
Bundle 'vim-scripts/taglist.vim'
Bundle 'majutsushi/tagbar'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-repeat'

Bundle 'ervandew/supertab'
Bundle 'Valloric/YouCompleteMe'
Bundle 'SirVer/ultisnips'

Bundle 'Lokaltog/vim-easymotion'
Bundle 'mtth/locate.vim'
Bundle 'godlygeek/tabular'
Bundle 'jiangmiao/auto-pairs'
Bundle 'reedes/vim-colors-pencil'
Bundle 'bling/vim-airline'
```

**Comment by mtth** [comment] 2015-05-26 17:23
Thanks. My suspicion is that one of the other plugins sets up a conflicting `autocmd`. Could you try disabling them all to confirm this? If that fixes it and it's not too tedious, it'd be most helpful to know which one creates the issue.

**Comment by mtth** [comment] 2015-10-23 01:30
Closing since this is likely a duplicate of https://github.com/mtth/locate.vim/issues/2 (syntastic is among the plugins above).

**Closed by mtth** 2015-10-23 01:30 UTC
